azureTenant: trygdeetaten.no
kafkaPool: nav-dev
environment: dev
db_tier: db-f1-micro
db_size: 10
db_highAvailability: false
db_pointInTimeRecovery: false
cpu: 300m
memory: 800Mi
replicas_min: 1
replicas_max: 2
external-host:
  - pdl-api.dev-fss-pub.nais.io
  - ereg-services.dev-fss-pub.nais.io
  - team-inntekt-proxy.dev-fss-pub.nais.io
  - flex-unleash-api.nav.cloud.nais.io
  - aareg-services-q1.dev-fss-pub.nais.io
flex-openapi-docs-ui: true
env:
  SPRING_PROFILES_ACTIVE: default,testdatareset,sykmeldinger
  PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: dev-fss.pdl.pdl-api
  FASIT_ENVIRONMENT_NAME: q1
  SYKEPENGESOKNAD_KVITTERINGER_URL: http://sykepengesoknad-kvitteringer
  SYKEPENGESOKNAD_KVITTERINGER_TOKENX_CLIENT_ID: dev-gcp:flex:sykepengesoknad-kvitteringer
  ISTILGANGSKONTROLL_URL: http://istilgangskontroll.teamsykefravr
  ISTILGANGSKONTROLL_AAD_CLIENT_ID: dev-gcp.teamsykefravr.istilgangskontroll
  FLEX_SYKETILFELLE_URL: http://flex-syketilfelle
  FLEX_SYKETILFELLE_AAD_CLIENT_ID: dev-gcp.flex.flex-syketilfelle
  SKRIVEMODUS: READWRITE
  DITT_SYKEFRAVAER_FRONTEND_CLIENT_ID: dev-gcp:flex:ditt-sykefravaer
  SYKEPENGESOKNAD_FRONTEND_CLIENT_ID: dev-gcp:flex:sykepengesoknad
  SPINNTEKTSMELDING_FRONTEND_CLIENT_ID: dev-gcp:helsearbeidsgiver:spinntektsmelding-frontend
  TOKENX_IDPORTEN_IDP: https://oidc-ver2.difi.no/idporten-oidc-provider/
  AIVEN_KAFKA_AUTO_OFFSET_RESET: latest
  EREG_URL: https://ereg-services.dev-fss-pub.nais.io
  YRKESSKADE_URL: http://yrkesskade-saker.yrkesskade
  YRKESSKADE_AAD_CLIENT_ID: dev-gcp.yrkesskade.yrkesskade-saker
  MEDLEMSKAP_VURDERING_URL: http://medlemskap-sykepenger-listener.medlemskap
  MEDLEMSKAP_VURDERING_AAD_CLIENT_ID: dev-gcp.medlemskap.medlemskap-sykepenger-listener
  INNTEKTSKOMPONENTEN_URL: https://team-inntekt-proxy.dev-fss-pub.nais.io/proxy/inntektskomponenten-q1/rs
  INNTEKTSKOMPONENTEN_AAD_CLIENT_ID: dev-fss.team-inntekt.inntektskomponenten
  SIGRUN_URL: https://team-inntekt-proxy.dev-fss-pub.nais.io/proxy/sigrun-q1
  SIGRUN_AAD_CLIENT_ID: dev-fss.team-inntekt.sigrun-q1
  INNSENDING_API_TOKENX_CLIENT_ID: dev-gcp:team-soknad:innsending-api
  INNSENDING_API_URL: http://innsending-api.team-soknad
  GRUNNBELOEP_API_URL: https://g.nav.no/api/v1
  HAG_API_ENABLED: true
  AAREG_URL: https://aareg-services-q1.dev-fss-pub.nais.io
  AAREG_AAD_CLIENT_ID: dev-fss.arbeidsforhold.aareg-services-nais-q1
