azureTenant: trygdeetaten.no
kafkaPool: nav-dev
environment: dev
db_tier: db-f1-micro
db_size: 10
cpu: 300m
memory: 640Mi
replicas_min: 1
replicas_max: 2
external-host:
  - pdl-api.dev-fss-pub.nais.io
  - flex-fss-proxy.dev-fss-pub.nais.io
  - ereg-services.dev-fss-pub.nais.io
  - team-inntekt-proxy.dev-fss-pub.nais.io
env:
  SPRING_PROFILES_ACTIVE: default,testdatareset,sykmeldinger
  PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: dev-fss.pdl.pdl-api
  FASIT_ENVIRONMENT_NAME: "q1"
  SYKEPENGESOKNAD_KVITTERINGER_URL: "http://sykepengesoknad-kvitteringer"
  SYKEPENGESOKNAD_KVITTERINGER_TOKENX_CLIENT_ID: dev-gcp:flex:sykepengesoknad-kvitteringer
  SYFOTILGANGSKONTROLL_URL: "http://syfo-tilgangskontroll.teamsykefravr"
  SYFOTILGANGSKONTROLL_AAD_CLIENT_ID: dev-gcp.teamsykefravr.syfo-tilgangskontroll
  FLEX_SYKETILFELLE_URL: "http://flex-syketilfelle"
  FLEX_SYKETILFELLE_AAD_CLIENT_ID: dev-gcp.flex.flex-syketilfelle
  SKRIVEMODUS: READWRITE
  DITT_SYKEFRAVAER_FRONTEND_CLIENT_ID: dev-gcp:flex:ditt-sykefravaer
  SYKEPENGESOKNAD_FRONTEND_CLIENT_ID: dev-gcp:flex:sykepengesoknad
  TOKENX_IDPORTEN_IDP: https://oidc-ver2.difi.no/idporten-oidc-provider/
  AIVEN_KAFKA_AUTO_OFFSET_RESET: latest
  FLEX_FSS_PROXY_AAD_CLIENT_ID: dev-fss.flex.flex-fss-proxy
  FLEX_FSS_PROXY_URL: https://flex-fss-proxy.dev-fss-pub.nais.io
  EGENMELDING_SYKMELDING_FOM: "2023-03-01T04:00:00.000000+01:00"
  EREG_URL: https://ereg-services.dev-fss-pub.nais.io
  YRKESSKADE_URL: http://yrkesskade-saker.yrkesskade
  YRKESSKADE_AAD_CLIENT_ID: dev-gcp.yrkesskade.yrkesskade-saker
  MEDLEMSKAP_VURDERING_URL: "http://medlemskap-sykepenger-listener.medlemskap"
  MEDLEMSKAP_VURDERING_AAD_CLIENT_ID: dev-gcp.medlemskap.medlemskap-sykepenger-listener
  INNTEKTSKOMPONENTEN_URL: "https://team-inntekt-proxy.dev-fss-pub.nais.io/proxy/inntektskomponenten-q1"
  INNTEKTSKOMPONENTEN_AAD_CLIENT_ID: dev-fss.team-inntekt.inntektskomponenten
