apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad-backend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 45
    timeout: 1
    periodSeconds: 5
    failureThreshold: 20
  readiness:
    path: /internal/isReady
    initialDelay: 45
    timeout: 1
    periodSeconds: 5
    failureThreshold: 20
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 600m
      memory: 2048Mi
    requests:
      cpu: 400m
      memory: 1024Mi
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  kafka:
    pool: {{kafkaPool}}
  gcp:
    sqlInstances:
      - name: sykepengesoknad
        type: POSTGRES_14
        tier: {{ db_tier }}
        diskType: SSD
        highAvailability: true
        diskSize: {{ db_size }}
        pointInTimeRecovery: false
        diskAutoresize: true
        databases:
          - name: sykepengesoknad
            envVarPrefix: DATABASE
        maintenance:
          day: 2
          hour: 2
  accessPolicy:
    outbound:
      external:
        - host: {{ schema_registry }}
      rules:
        - application: sykepengesoknad-backend-redis
        - application: flex-bucket-uploader
        - application: flex-syketilfelle
        - application: narmesteleder
          namespace: teamsykmelding
    inbound:
      rules:
        - application: flex-gateway
  envFrom:
    - configmap: loginservice-idporten
    - secret: sykepengesoknad-backend-redis-password
    - secret: sykepengesoknad-serviceuser
  env:
  {{#each env}}
     - name: {{@key}}
       value: {{this}}
  {{/each}}
