apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad-backend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/liveness
    initialDelay: 60
    timeout: 1
    periodSeconds: 5
    failureThreshold: 20
  readiness:
    path: /internal/health/readiness
    initialDelay: 60
    timeout: 1
    periodSeconds: 5
    failureThreshold: 20
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 400m
      memory: 1024Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: {{azureTenant}}
  kafka:
    pool: {{kafkaPool}}
  tokenx:
    enabled: true
  gcp:
    sqlInstances:
      - name: sykepengesoknad
        type: POSTGRES_14
        tier: {{ db_tier }}
        diskType: SSD
        highAvailability: true
        diskSize: {{ db_size }}
        pointInTimeRecovery: true
        diskAutoresize: true
        databases:
          - name: sykepengesoknad
            envVarPrefix: DATABASE
            users:
              - name: bigquery-dataprodukt
              - name: bigquery-datastream
        maintenance:
          day: 2
          hour: 2
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  accessPolicy:
    outbound:
      rules:
        - application: sykepengesoknad-backend-redis
        - application: sykepengesoknad-kvitteringer
        - application: flex-syketilfelle
        - application: yrkesskade-saker
          namespace: yrkesskade
      external:
  {{#each external-host}}
        - host: {{this}}
  {{/each}}
    inbound:
      rules:
        - application: ditt-sykefravaer
        - application: sykepengesoknad
        - application: sykepengesoknad-arkivering-oppgave
        - application: sykepengesoknad-korrigering-metrikk
        - application: flex-intern-gateway
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: {{ syfomodiaperson_cluster }}
        - application: syfomodiaperson
          namespace: teamsykefravr
  envFrom:
    - secret: sykepengesoknad-backend-redis-password
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
