apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad-backend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/liveness
  readiness:
    path: /internal/health/readiness
  startup:
    path: /internal/health/liveness
    initialDelay: 40
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: {{azureTenant}}
  kafka:
    pool: {{kafkaPool}}
  tokenx:
    enabled: true
  redis:
    - instance: sessions
      access: readwrite
  gcp:
    sqlInstances:
      - name: sykepengesoknad
        type: POSTGRES_14
        diskType: SSD
        tier: {{db_tier}}
        diskSize: {{db_size}}
        highAvailability: {{db_highAvailability}}
        pointInTimeRecovery: {{db_pointInTimeRecovery}}
        diskAutoresize: true
        databases:
          - name: sykepengesoknad
            envVarPrefix: DATABASE
            users:
              - name: bigquery-dataprodukt
              - name: bigquery-datastream
        maintenance:
          day: 2
          hour: 2
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  accessPolicy:
    outbound:
      rules:
        - application: sykepengesoknad-kvitteringer
        - application: flex-syketilfelle
        - application: yrkesskade-saker
          namespace: yrkesskade
        - application: istilgangskontroll
          namespace: teamsykefravr
        - application: medlemskap-sykepenger-listener
          namespace: medlemskap
        - application: innsending-api
          namespace: team-soknad
      external:
  {{#each external-host}}
        - host: {{this}}
  {{/each}}
    inbound:
      rules:
        - application: ditt-sykefravaer
        - application: sykepengesoknad
        - application: sykepengesoknad-arkivering-oppgave
        - application: flex-internal-frontend
        - application: syfomodiaperson
          namespace: teamsykefravr
        - application: sparkel-dokumenter
          namespace: tbd
  envFrom:
    - secret: sykepengesoknad-backend-unleash-api-token
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
