azureTenant: nav.no
kafkaPool: nav-prod
environment: prod
db_tier: db-custom-4-15360
db_size: 250
db_highAvailability: true
db_pointInTimeRecovery: true
cpu: 500m
memory: 1230Mi
replicas_min: 3
replicas_max: 5
external-host:
  - pdl-api.prod-fss-pub.nais.io
  - ereg-services.prod-fss-pub.nais.io
  - team-inntekt-proxy.prod-fss-pub.nais.io
  - flex-unleash-api.nav.cloud.nais.io
  - aareg-services.prod-fss-pub.nais.io
env:
  SPRING_PROFILES_ACTIVE: default,sykmeldinger
  PDL_BASE_URL: https://pdl-api.prod-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: prod-fss.pdl.pdl-api
  FASIT_ENVIRONMENT_NAME: p
  SYKEPENGESOKNAD_KVITTERINGER_URL: http://sykepengesoknad-kvitteringer
  SYKEPENGESOKNAD_KVITTERINGER_TOKENX_CLIENT_ID: prod-gcp:flex:sykepengesoknad-kvitteringer
  ISTILGANGSKONTROLL_URL: http://istilgangskontroll.teamsykefravr
  ISTILGANGSKONTROLL_AAD_CLIENT_ID: prod-gcp.teamsykefravr.istilgangskontroll
  FLEX_SYKETILFELLE_URL: http://flex-syketilfelle
  FLEX_SYKETILFELLE_AAD_CLIENT_ID: prod-gcp.flex.flex-syketilfelle
  SKRIVEMODUS: READWRITE
  DITT_SYKEFRAVAER_FRONTEND_CLIENT_ID: prod-gcp:flex:ditt-sykefravaer
  SYKEPENGESOKNAD_FRONTEND_CLIENT_ID: prod-gcp:flex:sykepengesoknad
  SPINNTEKTSMELDING_FRONTEND_CLIENT_ID: prod-gcp:helsearbeidsgiver:spinntektsmelding-frontend
  TOKENX_IDPORTEN_IDP: https://oidc.difi.no/idporten-oidc-provider/
  EREG_URL: https://ereg-services.prod-fss-pub.nais.io
  YRKESSKADE_URL: http://yrkesskade-saker.yrkesskade
  YRKESSKADE_AAD_CLIENT_ID: prod-gcp.yrkesskade.yrkesskade-saker
  MEDLEMSKAP_VURDERING_URL: http://medlemskap-sykepenger-listener.medlemskap
  MEDLEMSKAP_VURDERING_AAD_CLIENT_ID: prod-gcp.medlemskap.medlemskap-sykepenger-listener
  INNTEKTSKOMPONENTEN_URL: https://team-inntekt-proxy.prod-fss-pub.nais.io/proxy/inntektskomponenten/rs
  INNTEKTSKOMPONENTEN_AAD_CLIENT_ID: prod-fss.team-inntekt.inntektskomponenten
  SIGRUN_URL: https://team-inntekt-proxy.prod-fss-pub.nais.io/proxy/sigrun
  SIGRUN_CLIENT_ID: prod-fss.team-inntekt.sigrun
  INNSENDING_API_TOKENX_CLIENT_ID: prod-gcp:team-soknad:innsending-api
  INNSENDING_API_URL: http://innsending-api.team-soknad
  GRUNNBELOEP_API_URL: https://g.nav.no/api/v1
  AAREG_URL: https://aareg-services.prod-fss-pub.nais.io
  AAREG_AAD_CLIENT_ID: prod-fss.arbeidsforhold.aareg-services-nais
