azureTenant: nav.no
kafkaPool: nav-prod
environment: prod
db_tier: db-custom-2-3840
db_size: 250
replicas_min: 2
replicas_max: 3
schema_registry: "kafka-schema-registry.nais.adeo.no"
env:
  PDL_BASE_URL: https://pdl-api.prod-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: prod-fss.pdl.pdl-api
  ON_PREM_BOOTSTRAP_SERVERS: "a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443"
  ON_PREM_SCHEMA_REGISTRY_URL: "https://kafka-schema-registry.nais.adeo.no"
  FASIT_ENVIRONMENT_NAME: "p"
  JULESOKNAD_CRON: "0 0 5 * * ?"
  SYFOSOKNAD_CRON: "0 0 1 * * ?"
  FLEX_BUCKET_UPLOADER_URL: "http://flex-bucket-uploader"
  FLEX_BUCKET_UPLOADER_AAD_CLIENT_ID: prod-gcp.flex.flex-bucket-uploader
  NARMESTELEDER_AAD_CLIENT_ID: prod-gcp.teamsykmelding.narmesteleder
  NARMESTELEDER_URL: "http://narmesteleder.teamsykmelding"
  SYFOTILGANGSKONTROLL_URL: "https://syfo-tilgangskontroll.prod-fss-pub.nais.io"
  SYFOTILGANGSKONTROLL_AAD_CLIENT_ID: prod-fss.teamsykefravr.syfo-tilgangskontroll
  FLEX_SYKETILFELLE_URL: "http://flex-syketilfelle"
  FLEX_SYKETILFELLE_AAD_CLIENT_ID: prod-gcp.flex.flex-syketilfelle
