package no.nav.helse.flex.domain

enum class Svartype {
    JA_NEI,
    CHECKBOX,
    CHECKBOX_GRUPPE,
    CHECKBOX_PANEL,
    DATO,
    PERIODE,
    PERIODER,
    TIMER,
    FRITEKST,
    LAND,
    COMBOBOX_SINGLE,
    COMBOBOX_MULTI,
    IKKE_RELEVANT,
    GRUPPE_AV_UNDERSPORSMAL,
    PROSENT,
    RADIO_GRUPPE,
    RADIO_GRUPPE_TIMER_PROSENT,
    RADIO_GRUPPE_UKEKALENDER,
    RADIO,
    TALL,
    INFO_BEHANDLINGSDAGER,
    KVITTERING,
    DATOER,
    BELOP,
    KILOMETER
}
