package no.nav.helse.flex.controller.domain.sykepengesoknad

enum class RSSoknadstype {
    SELVSTENDIGE_OG_FRILANSERE,
    OPPHOLD_UTLAND,
    ARBEIDSTAKERE,
    ARBEIDSLEDIG,
    BEHANDLINGSDAGER,
    ANNET_ARBEIDSFORHOLD,
    REISETILSKUDD,
    GRADERT_REISETILSKUDD,
    FRISKMELDT_TIL_ARBEIDSFORMIDLING,
}
