azureTenant: trygdeetaten.no
kafkaPool: nav-dev
environment: dev
db_tier: db-f1-micro
db_size: 10
replicas_min: 1
replicas_max: 2
env:
  SPRING_PROFILES_ACTIVE: default,testdatareset
  PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: dev-fss.pdl.pdl-api
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443"
  FASIT_ENVIRONMENT_NAME: "q1"
  SYFOTILGANGSKONTROLL_URL: "https://syfo-tilgangskontroll.nais.preprod.local/syfo-tilgangskontroll"
  SYFOSMREGISTER_URL: "http://syfosmregister.teamsykmelding"
  SYFOSMREGISTER_AAD_CLIENT_ID: dev-fss.teamsykmelding.syfosmregister
  JULESOKNAD_CRON: "0 0/5 * * * ?"
  SYFOSOKNAD_CRON: "0 0/3 * * * ?"
  FLEX_BUCKET_UPLOADER_URL: "https://flex-bucket-uploader.dev.intern.nav.no"
  FLEX_BUCKET_UPLOADER_AAD_CLIENT_ID: dev-gcp.flex.flex-bucket-uploader
  NARMESTELEDER_AAD_CLIENT_ID: dev-gcp.teamsykmelding.narmesteleder
  NARMESTELEDER_URL: "https://narmesteleder.dev.intern.nav.no"
  SYFOTILGANGSKONTROLL_AAD_CLIENT_ID: dev-fss.teamsykefravr.syfo-tilgangskontroll
  FLEX_SYKETILFELLE_URL: "https://flex-syketilfelle.dev.intern.nav.no"
  FLEX_SYKETILFELLE_AAD_CLIENT_ID: dev-gcp.flex.flex-syketilfelle
