CREATE TABLE SENDING_FEILET (
  SENDING_FEILET_ID     NUMBER(19)    NOT NULL PRIMARY KEY,
  SYKEPENGESOKNAD_UUID  VARCHAR2(100) NOT NULL UNIQUE,
  CONSTRAINT SYKEPENGESOKNAD_UUID_FK FOREIGN KEY (SYKEPENGESOKNAD_UUID) REFERENCES SYKEPENGESOKNAD (SYKEPENGESOKNAD_UUID)
);

CREATE SEQUENCE SENDING_FEILET_ID_SEQ START WITH 1;