ALTER TABLE SYKEPENGESOKNAD ADD ARBEIDSGIVER          VARCHAR2(100) NULL;
ALTER TABLE SYKEPENGESOKNAD ADD ARBEIDSSITUASJON      VARCHAR2(20)  NULL;
ALTER TABLE SYKEPENGESOKNAD ADD START_SYKEFORLOP      DATE          NULL;
ALTER TABLE SYKEPENGESOKNAD ADD SYKMELDING_UTSKREVET  DATE          NULL;

UPDATE SYKEPENGESOKNAD S
  SET ARBEIDSSITUASJON = 'FRILANSER'
  WHERE EXISTS (SELECT NULL FROM SPORSMAL SPM
                  WHERE TAG = 'INNTEKTSKILDE_FRILANSER_SELVSTENDIG'
                  AND TEKST = 'Selvstendig næringsdrivende'
                  AND S.SYKEPENGESOKNAD_ID = SPM.SYKEPENGESOKNAD_ID);

UPDATE SYKEPENGESOKNAD S
  SET ARBEIDSSITUASJON = 'NAERINGSDRIVENDE'
  WHERE EXISTS (SELECT NULL FROM SPORSMAL SPM
                  WHERE TAG = 'INNTEKTSKILDE_FRILANSER_SELVSTENDIG'
                  AND TEKST = 'Frilanser'
                  AND S.SYKEPENGESOKNAD_ID = SPM.SYKEPENGESOKNAD_ID);

CREATE TABLE SOKNADPERIODE (
  SOKNADPERIODE_ID     NUMBER(19)  NOT NULL PRIMARY KEY,
  SYKEPENGESOKNAD_ID    NUMBER(19)  NOT NULL,
  FOM                   DATE        NOT NULL,
  TOM                   DATE        NOT NULL,
  GRAD                  NUMBER(5)   NOT NULL,
  CONSTRAINT PERIODE_SOKNAD_ID_FK FOREIGN KEY (SYKEPENGESOKNAD_ID) REFERENCES SYKEPENGESOKNAD (SYKEPENGESOKNAD_ID)
);

CREATE SEQUENCE SOKNADPERIODE_ID_SEQ START WITH 1;
CREATE INDEX SOKNADPERIODE_SOKNAD_ID_index ON SOKNADPERIODE(SYKEPENGESOKNAD_ID);