CREATE TABLE SYKEPENGESOKNAD (
  SYKEPENGESOKNAD_ID    NUMBER(19)    NOT NULL PRIMARY KEY,
  SYKEPENGESOKNAD_UUID  VARCHAR2(100) NOT NULL UNIQUE,
  AKTOR_ID              VARCHAR2(20)  NOT NULL,
  SOKNADSTYPE           VARCHAR2(100) NOT NULL,
  STATUS                VARCHAR2(100) NOT NULL,
  FOM                   VARCHAR2(20)  NOT NULL,
  TOM                   VARCHAR2(20)  NOT NULL,
  OPPRETTET_DATO        VARCHAR2(20)  NOT NULL,
  SYKMELDING_UUID       VARCHAR2(100) NOT NULL
);

CREATE TABLE SPORSMAL (
  SPORSMAL_ID         NUMBER(19)    NOT NULL PRIMARY KEY,
  SYKEPENGESOKNAD_ID  NUMBER(19)    NOT NULL,
  UNDER_SVAR_ID       NUMBER(19),
  TEKST               VARCHAR2(400),
  UNDERTEKST          VARCHAR2(100),
  TAG                 VARCHAR2(50)  NOT NULL,
  CONSTRAINT SYKEPENGESOKNAD_ID_FK FOREIGN KEY (SYKEPENGESOKNAD_ID) REFERENCES SYKEPENGESOKNAD (SYKEPENGESOKNAD_ID)
);

CREATE TABLE SVAR (
  SVAR_ID              NUMBER(19)   NOT NULL PRIMARY KEY,
  SPORSMAL_ID          NUMBER(19)   NOT NULL,
  SVARTYPE             VARCHAR2(20) NOT NULL,
  MIN                  VARCHAR2(20),
  MAX                  VARCHAR2(20),
  KRITERIE_FOR_VISNING VARCHAR2(20),
  CONSTRAINT SPORSMAL_ID_FK FOREIGN KEY (SPORSMAL_ID) REFERENCES SPORSMAL (SPORSMAL_ID)
);

ALTER TABLE SPORSMAL
  ADD CONSTRAINT UNDER_SVAR_ID_FK FOREIGN KEY (UNDER_SVAR_ID) REFERENCES SVAR (SVAR_ID);

CREATE TABLE SVARVERDI (
  SVARVERDI_ID  NUMBER(19)   NOT NULL PRIMARY KEY,
  SVAR_ID       NUMBER(19)   NOT NULL,
  VERDI         VARCHAR2(20) NOT NULL,
  SVARVERDITYPE VARCHAR2(20),
  CONSTRAINT SVAR_ID_FK FOREIGN KEY (SVAR_ID) REFERENCES SVAR (SVAR_ID)
);

CREATE SEQUENCE SYKEPENGESOKNAD_ID_SEQ START WITH 1;
CREATE SEQUENCE SPORSMAL_ID_SEQ START WITH 1;
CREATE SEQUENCE SVAR_ID_SEQ START WITH 1;
CREATE SEQUENCE SVARVERDI_ID_SEQ START WITH 1;