CREATE INDEX SYKEPENGESOKNAD_AKTOR_ID_index ON SYKEPENGESOKNAD(AKTOR_ID);
CREATE INDEX SYKEPENGESOKNAD_STATUS_index ON SYKEPENGESOKNAD(STATUS);
CREATE INDEX SPORSMAL_SOKNAD_ID_index ON SPORSMAL(SYKEPENGESOKNAD_ID);
CREATE INDEX SVAR_SPORSMAL_ID_index ON SVAR(SPORSMAL_ID);