ALTER TABLE SYKEPENGESOKNAD
  MODIFY OPPRETTET_DATO DATE NULL;

UPDATE SYKEPENGESOKNAD
SET ARBEIDSGIVER_NAVN = ARBEIDSGIVER
WHERE ARBEIDSGIVER_NAVN IS NULL
  AND ARBEIDSGIVER IS NOT NULL;

UPDATE SYKEPENGESOKNAD
SET SENDT_NAV = INNSENDT_DATO
WHERE SENDT_NAV IS NULL
  AND INNSENDT_DATO IS NOT NULL;

UPDATE SYKEPENGESOKNAD
SET SYKMELDING_SKREVET = SYKMELDING_UTSKREVET
WHERE SYKMELDING_SKREVET IS NULL
  AND SYKMELDING_UTSKREVET IS NOT NULL;

UPDATE SYKEPENGESOKNAD
SET OPPRETTET = OPPRETTET_DATO
WHERE OPPRETTET IS NULL
  AND OPPRETTET_DATO IS NOT NULL;
