ALTER TABLE SYKEPENGESOKNAD
  MODIFY OPPRETTET TIMESTAMP NOT NULL;

ALTER TABLE SYKEPENGESOKNAD
  DROP COLUMN ARBEIDSGIVER;
ALTER TABLE SYKEPENGESOKNAD
  DROP COLUMN INNSENDT_DATO;
ALTER TABLE SYKEPENGESOKNAD
  DROP COLUMN SYKMELDING_UTSKREVET;
ALTER TABLE SYKEPENGESOKNAD
  DROP COLUMN OPPRETTET_DATO;
