
DROP TABLE SVARVERDI;

ALTER TABLE SPORSMAL
  DROP CONSTRAINT UNDER_SVAR_ID_FK;

DROP TABLE SVAR;
DROP TABLE SPORSMAL;
DROP SEQUENCE SVARVERDI_ID_SEQ;

CREATE TABLE SPORSMAL (
  SPORSMAL_ID          NUMBER(19)     NOT NULL PRIMARY KEY,
  SYKEPENGESOKNAD_ID   NUMBER(19)     NOT NULL,
  UNDER_SPORSMAL_ID    NUMBER(19),
  TEKST                VARCHAR2(400),
  UNDERTEKST           VARCHAR2(100),
  TAG                  VARCHAR2(50)   NOT NULL,
  SVARTYPE             VARCHAR2(20)   NOT NULL,
  MIN                  VARCHAR2(20),
  MAX                  VARCHAR2(20),
  KRITERIE_FOR_VISNING VARCHAR2(20),
  CONSTRAINT SYKEPENGESOKNAD_ID_FK FOREIGN KEY (SYKEPENGESOKNAD_ID) REFERENCES SYKEPENGESOKNAD (SYKEPENGESOKNAD_ID)
);

CREATE TABLE SVAR (
  SVAR_ID       NUMBER(19)    NOT NULL PRIMARY KEY,
  SPORSMAL_ID   NUMBER(19)    NOT NULL,
  VERDI         VARCHAR2(20)  NOT NULL,
  SVARVERDITYPE VARCHAR2(20),
  CONSTRAINT SPORSMAL_ID_FK FOREIGN KEY (SPORSMAL_ID) REFERENCES SPORSMAL (SPORSMAL_ID)
);