ALTER TABLE SYKEPENGESOKNAD
  ADD (
    ARBEIDSGIVER_ORGNUMMER VARCHAR2(15),
    ARBEIDSGIVER_NAVN VARCHAR2(100),
    ARBEIDSGIVER_FORSKUTTERER VARCHAR2(10),
    SENDT_ARBEIDSGIVER TIMESTAMP,
    SENDT_NAV TIMESTAMP,
    SYKMELDING_SKREVET TIMESTAMP,
    OPPRETTET TIMESTAMP
    );
