ALTER TABLE SYKEPENGESOKNAD MODIFY FOM VARCHAR2(20) NULL;
ALTER TABLE SYKEPENGESOKNAD MODIFY TOM VARCHAR2(20) NULL;
ALTER TABLE SYKEPENGESOKNAD MODIFY SYKMELDING_UUID VARCHAR2(100) NULL;

ALTER TABLE SPORSMAL MODIFY UNDERTEKST   VARCHAR2(400);