CREATE TABLE DODSMELDING (
  DODSMELDING_ID        NUMBER(19)    NOT NULL PRIMARY KEY,
  AKTOR_ID              VARCHAR2(20)  NOT NULL UNIQUE,
  DODSDATO              DATE          NOT NULL,
  MELDING_MOTTATT_DATO  DATE          NOT NULL
);

CREATE SEQUENCE DODSMELDING_ID_SEQ START WITH 1;