CREATE TABLE JULESOKNADKANDIDAT
(
    JULESOKNADKANDIDAT_ID NUMBER(19)    NOT NULL PRIMARY KEY,
    SYKEPENGESOKNAD_UUID  VARCHAR2(100) NOT NULL UNIQUE,
    OPPRETTET             TIMESTAMP     NOT NULL
);

CREATE SEQUENCE JULESOKNADKANDIDAT_ID_SEQ START WITH 1;
