ALTER TABLE SYKEPENGESOKNAD MODIFY FOM DATE;
ALTER TABLE SYKEPENGESOKNAD MODIFY TOM DATE;
ALTER TABLE SYKEPENGESOKNAD MODIFY OPPRETTET_DATO DATE;
ALTER TABLE SYKEPENGESOKNAD MODIFY INNSENDT_DATO DATE;
