CREATE TABLE SYKEPENGESOKNAD
(
    ID                       VARCHAR DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    SYKEPENGESOKNAD_UUID     VARCHAR                  NOT NULL UNIQUE,
    SOKNADSTYPE              VARCHAR                  NOT NULL,
    STATUS                   VARCHAR                  NOT NULL,
    FOM                      DATE,
    TOM                      DATE,
    SYKMELDING_UUID          VARCHAR,
    AKTIVERT_DATO            DATE,
    KORRIGERER               VARCHAR,
    KORRIGERT_AV             VARCHAR,
    AVBRUTT_DATO             DATE,
    ARBEIDSSITUASJON         VARCHAR,
    START_SYKEFORLOP         DATE,
    ARBEIDSGIVER_ORGNUMMER   VARCHAR,
    ARBEIDSGIVER_NAVN        VARCHAR,
    SENDT_ARBEIDSGIVER       TIMESTAMP WITH TIME ZONE,
    SENDT_NAV                TIMESTAMP WITH TIME ZONE,
    SYKMELDING_SKREVET       TIMESTAMP WITH TIME ZONE,
    OPPRETTET                TIMESTAMP WITH TIME ZONE NOT NULL,
    OPPRINNELSE              VARCHAR,
    AVSENDERTYPE             VARCHAR,
    FNR                      VARCHAR(11),
    EGENMELDT_SYKMELDING     BOOLEAN,
    MERKNADER_FRA_SYKMELDING VARCHAR,
    UTLOPT_PUBLISERT         TIMESTAMP WITH TIME ZONE,
    AVBRUTT_FEILINFO         BOOLEAN
);

CREATE INDEX SYKEPENGESOKNAD_FNR_INDEX ON SYKEPENGESOKNAD (FNR);


CREATE TABLE SPORSMAL
(
    ID                   VARCHAR DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    SYKEPENGESOKNAD_ID   VARCHAR NOT NULL REFERENCES SYKEPENGESOKNAD (ID),
    UNDER_SPORSMAL_ID    VARCHAR REFERENCES SPORSMAL (ID),
    TEKST                VARCHAR,
    UNDERTEKST           VARCHAR,
    TAG                  VARCHAR NOT NULL,
    SVARTYPE             VARCHAR NOT NULL,
    MIN                  VARCHAR,
    MAX                  VARCHAR,
    KRITERIE_FOR_VISNING VARCHAR
);


CREATE INDEX SPORSMAL_SOKNAD_ID_INDEX
    ON SPORSMAL (SYKEPENGESOKNAD_ID);


CREATE INDEX UNDER_SPORSMAL_ID_INDEX
    ON SPORSMAL (UNDER_SPORSMAL_ID);


CREATE TABLE SVAR
(
    ID          VARCHAR DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    SPORSMAL_ID VARCHAR NOT NULL REFERENCES SPORSMAL (ID),
    VERDI       VARCHAR NOT NULL
);



CREATE TABLE SOKNADPERIODE
(
    ID                 VARCHAR DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    SYKEPENGESOKNAD_ID VARCHAR NOT NULL REFERENCES SYKEPENGESOKNAD (ID),
    FOM                DATE    NOT NULL,
    TOM                DATE    NOT NULL,
    GRAD               INTEGER NOT NULL,
    SYKMELDINGSTYPE    VARCHAR
);


CREATE INDEX SOKNADPERIODE_SOKNAD_ID_INDEX
    ON SOKNADPERIODE (SYKEPENGESOKNAD_ID);


CREATE TABLE DODSMELDING
(
    ID                   VARCHAR DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    FNR                  VARCHAR(11)              NOT NULL UNIQUE,
    DODSDATO             DATE                     NOT NULL,
    MELDING_MOTTATT_DATO TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE JULESOKNADKANDIDAT
(
    ID                   VARCHAR DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    SYKEPENGESOKNAD_UUID VARCHAR                  NOT NULL UNIQUE,
    OPPRETTET            TIMESTAMP WITH TIME ZONE NOT NULL
);
