CREATE TABLE FORSKUTTERING
(
    ID                        VARCHAR(36) DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    OPPDATERT                 TIMESTAMP WITH TIME ZONE NOT NULL,
    NARMESTE_LEDER_ID         UUID UNIQUE,
    ORGNUMMER                 VARCHAR                  NOT NULL,
    BRUKER_FNR                VARCHAR                  NOT NULL,
    ARBEIDSGIVER_FORSKUTTERER BOOLEAN,
    AKTIV_FOM                 DATE                     NOT NULL,
    AKTIV_TOM                 DATE NULL,
    TIMESTAMP                 TIMESTAMP WITH TIME ZONE NOT NULL
);


CREATE INDEX BRUKER_FNR_IDX ON FORSKUTTERING (BRUKER_FNR);
