name: "Deploy topic"
on:
  push:
    paths:
      - nais/topics/**
      - .github/workflows/topic.yml
jobs:
  deploy-topic-to-dev:
    if: github.ref_name == 'main' || startsWith(github.ref_name, 'dev-')
    name: Deploy topic to dev-gcp
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy sykepengesoknad topic to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/topics/sykepengesoknad-topic.yaml
          VARS: nais/topics/dev.json
      - name: Deploy sykmeldinger sendt retry to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/topics/sykmeldinger-sendt-retry.yaml
          VARS: nais/topics/dev.json
      - name: Deploy sykepengesoknad aktivering to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/topics/sykepengesoknad-aktivering-topic.yaml
          VARS: nais/topics/dev.json

  deploy-topic-to-prod:
    if: github.ref_name == 'main'
    name: Deploy topic to prod-gcp
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy sykepengesoknad topic to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/topics/sykepengesoknad-topic.yaml
          VARS: nais/topics/prod.json
      - name: Deploy sykmeldinger sendt retry topic to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/topics/sykmeldinger-sendt-retry.yaml
          VARS: nais/topics/prod.json
      - name: Deploy sykepengesoknad aktivering to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/topics/sykepengesoknad-aktivering-topic.yaml
          VARS: nais/topics/prod.json
