name: "Deploy topic"
on:
  push:
    paths:
      - nais/topics/**
      - .github/workflows/topic.yml
jobs:
  deploy-topic-to-dev:
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/dev-')
    name: Deploy topic to dev-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy sykepengesoknad topic to dev-gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/topics/sykepengesoknad-topic.yaml
          VARS: nais/topics/dev.json
      - name: Deploy sykmeldinger sendt retry to dev-gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/topics/sykmeldinger-sendt-retry.yaml
          VARS: nais/topics/dev.json
      - name: Deploy sykepengesoknad aktivering to dev-gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/topics/sykepengesoknad-aktivering-topic.yaml
          VARS: nais/topics/dev.json

  deploy-topic-to-prod:
    if: github.ref == 'refs/heads/master'
    name: Deploy topic to prod-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy sykepengesoknad topic to prod-gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/topics/sykepengesoknad-topic.yaml
          VARS: nais/topics/prod.json
      - name: Deploy sykmeldinger sendt retry topic to prod-gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/topics/sykmeldinger-sendt-retry.yaml
          VARS: nais/topics/prod.json
      - name: Deploy sykepengesoknad aktivering to prod-gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/topics/sykepengesoknad-aktivering-topic.yaml
          VARS: nais/topics/prod.json
